"""add created_at to log breaks

Revision ID: 142e476a2eec
Revises: 1c93d701ff15
Create Date: 2025-05-10 20:34:47.312115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '142e476a2eec'
down_revision: Union[str, None] = '1c93d701ff15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_breaks', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('log_breaks', 'created_at')
    # ### end Alembic commands ###
