"""update delivery model locations

Revision ID: 1c93d701ff15
Revises: f5fef88243b4
Create Date: 2025-05-05 12:16:20.929927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c93d701ff15'
down_revision: Union[str, None] = 'f5fef88243b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('pickup_location_id', sa.Integer(), nullable=False))
    op.add_column('deliveries', sa.Column('dropoff_location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'deliveries', 'locations', ['pickup_location_id'], ['id'])
    op.create_foreign_key(None, 'deliveries', 'locations', ['dropoff_location_id'], ['id'])
    op.drop_column('deliveries', 'pickup_location')
    op.drop_column('deliveries', 'dropoff_location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('dropoff_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('deliveries', sa.Column('pickup_location', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_constraint(None, 'deliveries', type_='foreignkey')
    op.drop_column('deliveries', 'dropoff_location_id')
    op.drop_column('deliveries', 'pickup_location_id')
    # ### end Alembic commands ###
