"""add delivery, vehicle model

Revision ID: 9ca81d2d3c84
Revises: ce84585bb260
Create Date: 2025-04-28 18:11:27.245828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca81d2d3c84'
down_revision: Union[str, None] = 'ce84585bb260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('maintenance_due_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('pickup_location', sa.String(length=255), nullable=False),
    sa.Column('dropoff_location', sa.String(length=255), nullable=False),
    sa.Column('package_details', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_TRANSIT', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('delivery_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('drivers', sa.Column('vehicle_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'drivers', ['vehicle_id'])
    op.create_foreign_key(None, 'drivers', 'vehicles', ['vehicle_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_constraint(None, 'drivers', type_='unique')
    op.drop_column('drivers', 'vehicle_id')
    op.drop_table('deliveries')
    op.drop_table('vehicles')
    # ### end Alembic commands ###
