"""add location to log breaks

Revision ID: f5fef88243b4
Revises: 87b564e7e948
Create Date: 2025-05-05 08:41:59.854242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5fef88243b4'
down_revision: Union[str, None] = '87b564e7e948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_breaks', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'log_breaks', 'locations', ['location_id'], ['id'])
    op.drop_column('log_breaks', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('log_breaks', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'log_breaks', type_='foreignkey')
    op.drop_column('log_breaks', 'location_id')
    # ### end Alembic commands ###
